% Private helper shared within +postprocessing (see extractShapeFeatures.m).
function nucCycleInfo = applyCycleQC(nucCycleInfo, P)

    isValidCycle = ...
        nucCycleInfo.CycleLength >= P.minCycleLength & ...
        nucCycleInfo.CycleLength <= P.maxCycleLength & ...
        nucCycleInfo.TotalAmplitudeMaxMinusMin >= P.minAmplitude & ...
        nucCycleInfo.TroughPhase >= P.minTroughPhase & ...
        nucCycleInfo.TroughPhase <= P.maxTroughPhase & ...
        nucCycleInfo.NaNFractionTotal < P.maxNaNFractionTotal;

    nucCycleInfo.IsValidCycle = isValidCycle;

    fprintf("Valid cycles: %d / %d\n", sum(isValidCycle), height(nucCycleInfo));
end

