% Private helper shared within +postprocessing (see extractShapeFeatures.m).
function F = initializeFeatureStruct(n)

    names = [ ...
        "CytoDistanceCorr", "CytoDistanceRMSE", "CytoThresholdCorr", "CytoThresholdRMSE", ...
        "TroughIdxNorm", "InterphaseStartIdx", "InterphaseEndIdx", "LateStartIdx", "LateEndIdx", ...
        "InterphaseStartFrame", "InterphaseEndFrame", ...
        "InterphaseNucMean", "InterphaseCytoMean", "InterphaseNucCytoRatioMean", ...
        "InterphaseNucCytoRatioMax", "InterphaseNucCytoRatioP90", ...
        "EarlyInterphaseNucCytoRatioMean", "LateInterphaseNucCytoRatioMean", ...
        "InterphaseNucCytoRatioIncrease", "InterphaseNucCytoRatioSlope", ...
        "InterphaseNucMinusCytoMean", "LateNucMean", "LateCytoMean", ...
        "LateActivationScore_nucShape", "TimeToHalfActivation_nuc", "PeakPhase_nuc", "MaxSlopeLate_nucShape", ...
        "InterphaseNucVolMean", "InterphaseDropletVolMean", "InterphaseNCvolRatioMean", ...
        "CycleMeanNucVol", "CycleMeanNCvolRatio", ...
        "NucVolValidFraction", "NCvolRatioValidFraction", ...
        "InterphaseNucVolValidFraction", "InterphaseNCvolRatioValidFraction"];

    for i = 1:numel(names)
        F.(names(i)) = nan(n, 1);
    end

    F.InterphaseEndReason = strings(n, 1);
end

